---
version: '3.7'
services:
  pmm-managed-server-external-pmm:
    build:
      context: .
      args:
        PMM_VERSION: ${PMM_VERSION:-perconalab/pmm-server:dev-latest}
      dockerfile: devcontainer.Dockerfile
    container_name: pmm-managed-server-external-pmm
    hostname: pmm-managed-server
    networks:
      - ${NETWORK:-default}
    environment:
      - GO_VERSION=${GO_VERSION:-1.18.x}
      - REVIEWDOG_GITHUB_API_TOKEN=${REVIEWDOG_GITHUB_API_TOKEN}
      - ENABLE_DBAAS=${ENABLE_DBAAS:-0}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - ENABLE_ALERTING=1
      - ENABLE_BACKUP_MANAGEMENT=1
#      - PERCONA_TEST_SAAS_HOST=check.localhost
#      - PERCONA_TEST_TELEMETRY_INTERVAL=10s
#      - PERCONA_TEST_TELEMETRY_RETRY_BACKOFF=10s
#      - PMM_DEBUG=1

    extra_hosts:
      - pmm-managed:${PMM_MANAGED_HOST:-127.0.0.1}
      - host.docker.internal:host-gateway
      - portal.localhost:${PORTAL_HOST:-host-gateway}
      - check.localhost:${PORTAL_CHECK_HOST:-host-gateway}
      - pmm.localhost:${PORTAL_PMM_HOST:-host-gateway}
      - check-dev.percona.com:${PORTAL_PMM_HOST:-host-gateway}

    # for delve
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # see https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug#what-to-do
    ulimits:
      memlock: 67108864

    ports:
      - ${PMM_HTTP_PORT:-80}:80
      - ${PMM_HTTPS_PORT:-443}:443
      # PG
      - ${PMM_PG_PORT:-15432}:5432
      # Graphana
      - ${PMM_GRAFANA_PORT:-3000}:3000
      # VM
      - ${PMM_VM_PORT_NOTIFIER:-9093}:9093
      - ${PMM_VM_PORT_TCP:-9090}:9090
      - ${PMM_VM_PORT_HTTP:-8880}:8880
      # CH
      - ${PMM_CH_PORT_TCP:-11000}:9000
      - ${PMM_CH_PORT_HTTP:-11123}:8123
    volumes:
      - ./.devcontainer/etc-patched/nginx/pmm.conf:/etc/nginx/conf.d/pmm.conf:ro
      - ./.devcontainer/etc-patched/supervisord.d/:/etc/supervisord.d/:ro
      - ./.devcontainer/sync/etc/victoriametrics:/etc/victoriametrics:ro
      - ./:/root/go/src/github.com/percona/pmm
      - ./Makefile.devcontainer:/root/go/src/github.com/percona/pmm/Makefile:ro
      - go-modules:/root/go/pkg/mod # Put modules cache into a separate volume
      - /root/go/src/github.com/percona/pmm/bin # Let to have different binaries in devcontainer and on local machine
volumes:
  go-modules:
