services:
  alertmanager:
    host: "http://prime-pmm-1"
    dir_user: "pmm"
    dir_group: "pmm"
    dir: "/srv/alertmanager"
    cert_dir: "/srv/alertmanager/cert"
    data_dir: "/srv/alertmanager/data"
    config_path: "/etc/alertmanager.yml"
    base_config_path: "/srv/alertmanager/alertmanager.base.yml"
  victoria_metrics:
    before_config_reload_delay: "0"
    configuration_update_timeout: "10s"
    scrape_config_path: # is set via CLI flag `victoriametrics-config`
    base_prometheus_config_path: "/srv/prometheus/prometheus.base.yml"
    victoriametrics_dir_user: "pmm"
    victoriametrics_dir_group: "pmm"
    victoriametrics_dir: "/srv/victoriametrics"
    victoriametrics_data_dir: "/srv/victoriametrics/data"
  platform:
    skip_tls_verification: false
  telemetry:
    enabled: true
    load_defaults: true
    datasources:
      VM:
        enabled: true
        timeout: 2s
        address: http://localhost:9090/prometheus
      QANDB_SELECT:
        enabled: true
        timeout: 2s
        dsn: tcp://localhost:9000?database=pmm&block_size=10000&pool_size=2
      PMMDB_SELECT:
        enabled: true
        timeout: 10s
        use_separate_credentials: false
        separate_credentials:
          username: pmm
          password: pmm
    reporting:
      send_on_start: false
      interval: 24h
      interval_env: "PERCONA_TEST_TELEMETRY_INTERVAL"
      retry_backoff: 1h
      retry_backoff_env: "PERCONA_TEST_TELEMETRY_RETRY_BACKOFF"
      retry_count: 20
      send_timeout: 5s
